### ISSUE TITLE
Add unit tests for Uniswap

### ISSUE THREAD

**Issue by stefanmendoza** [perich/ethereum-dex-prices-service#18]
To ensure the library is functioning properly, unit tests should be included for Uniswap. Since this exchange uses the token metadata provided as part of the library as well as the [`ethers` library](https://github.com/ethers-io/ethers.js), we should think about creating a mock module for `ethers` as there would be some reusability across the Airswap and Bancor tests as well. Consideration should be given to available test tools related to the `ethers` library if any exist.

**Comment by stefanmendoza** [comment]
@grahamperich I've started working on adding these tests 👍

**Comment by grahamperich** [comment]
nice, totally agree on all points

**Comment by stefanmendoza** [comment]
@grahamperich I'll be picking this back up this week!
