### ISSUE TITLE
cli.js require(main) error

### ISSUE THREAD

**Issue by lion9901** [perich/ethereum-dex-prices-service#38]
Just a small bug that is probably resolved in next release.
After following the instructions form the Quickstart, the cli.js command fails.
`yarn search buy 500 ETH`
The issue is coming from the import in cli.js.
`const { main } = require('../main')`
As there is no main file, replacing with below fixed the issue.
`const { main } = require('../index')`

**Comment by perich** [comment]
fixed https://github.com/perich/ethereum-dex-prices-service/commit/75e91669a830308078f01126972e77ca2185a527
