### ISSUE TITLE
Eth2Dai closed

### ISSUE THREAD

**Issue by marcuswin** [perich/ethereum-dex-prices-service#43]
Eth2Dai now changed on Oasis.
New address: 0x8018280076d7fA2cAa1147e441352E8a89e1DDbe

**Comment by perich** [comment]
Looks like the contract may be using some of the same methods, so this might be a quick fix.

The `Eth2Dai` class uses `getBuyAmount` and `getPayAmount`, which seem to be supported in the Oasis contract as well: https://etherscan.io/address/0x39755357759ce0d7f32dc8dc45414cca409ae24e?utm_source=StateOfTheDApps#readContract

**Comment by perich** [comment]
Looks like the `0x39755357759cE0d7f32dC8dC45414CCa409AE24e` is still correct, however it will need to be changed after February 8th per this post: 

https://www.reddit.com/r/MakerDAO/comments/euplem/oasisdex_contract_will_be_upgraded_on_8th_feb_2020/

also see #45
